blog/urls.py
#!/usr/bin/python

"""
编写者:沫
时间:08:45 下午
"""
from django.urls import path
from . import views

# django 的做法是把不同的网址对应的处理函数写在一个 urls.py 文件里，当用户访问某个网址时，django 就去会这个文件里找
# 如果找到这个网址，就会调用和它绑定在一起的处理函数（叫做视图函数）
# 我们首先从 django.urls 导入了 path 函数，又从当前目录下导入了 views 模块。
# 然后我们把网址和处理函数的关系写在了 urlpatterns 列表里
# 绑定关系的写法是把网址和对应的处理函数作为参数传给 path 函数（第一个参数是网址，第二个参数是处理函数）
# 另外我们还传递了另外一个参数 name，这个参数的值将作为处理函数 index 的别名，这在以后会用到

# 在 blogProject 目录下（即 settings.py 所在的目录），原本就有一个 urls.py 文件，这是整个工程项目的 URL 配置文件。
# 而我们这里新建了一个 urls.py 文件，且位于 blog 应用下。这个文件将用于 blog 应用相关的 URL 配置，这样便于模块化管理。不要把两个文件搞混了
# 首页视图匹配的 URL 去掉域名后其实就是一个空的字符串。
# 对文章详情视图而言，每篇文章对应着不同的 URL。
# 比如我们可以把文章详情页面对应的视图设计成这个样子：
# 当用户访问 <网站域名>/posts/1/ 时，显示的是第一篇文章的内容，
# 而当用户访问 <网站域名>/posts/2/ 时，显示的是第二篇文章的内容，
# 这里数字代表了第几篇文章，也就是数据库中 Post 记录的 id

app_name = 'blog'
urlpatterns = [
    # path('', views.index, name='index'),
    # 前面已经说过每一个 URL 对应着一个视图函数，这样当用户访问这个 URL 时，
    # Django 就知道调用哪个视图函数去处理这个请求了。
    # 在 Django 中 URL 模式的配置方式就是通过 url 函数将 URL 和视图函数绑定。
    # 比如 path('', views.index, name='index')，它的第一个参数是 URL 模式，第二个参数是视图函数 index。
    # 对 url 函数来说，第二个参数传入的值必须是一个函数。
    # 而 IndexView 是一个类，不能直接替代 index 函数。
    # 好在将类视图转换成函数视图非常简单，只需调用类视图的 as_view() 方法即可（至于 as_view 方法究竟是如何将一个类转换成一个函数的目前不必关心，
    # 只需要在配置 URL 模式是调用 as_view 方法就可以了。
    # 具体的实现我们以后会专门开辟一个专栏分析类视图的源代码，到时候就能看出 django 使用的魔法了）。
    path('', views.IndexView.as_view(), name='index'),

    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    # 这里 'posts/<int:pk>/' 刚好匹配我们上面定义的 URL 规则。
    # 这条规则的含义是，以 posts/ 开头，后跟一个整数，并且以 / 符号结尾，如 posts/1/、 posts/255/ 等都是符合规则的，
    # 此外这里 <int:pk> 是 django 路由匹配规则的特殊写法，
    # 其作用是从用户访问的 URL 里把匹配到的数字捕获并作为关键字参数传给其对应的视图函数 detail。
    # 比如当用户访问 posts/255/ 时（注意 django 并不关心域名，而只关心去掉域名后的相对 URL），<int:pk> 匹配 255，
    # 那么这个 255 会在调用视图函数 detail 时被传递进去，其参数名就是冒号后面指定的名字 pk，
    # 实际上视图函数的调用就是这个样子：detail(request, pk=255)。
    # 我们这里必须从 URL 里捕获文章的 id，因为只有这样我们才能知道用户访问的究竟是哪篇文章
    # django 的路由匹配规则有很多类型，除了这里的 int 整数类型，还有 str 字符类型、uuid 等，
    # 可以通过官方文档了解：https://docs.djangoproject.com/en/2.2/topics/http/urls/#path-converters
    # 此外我们通过 app_name='blog' 告诉 django 这个 urls.py 模块是属于 blog 应用的，这种技术叫做视图函数命名空间
    # 我们看到 blog\urls.py 目前有两个视图函数，
    # 并且通过 name 属性给这些视图函数取了个别名，分别是 index、detail。
    # 但是一个复杂的 django 项目可能不止这些视图函数，例如一些第三方应用中也可能有叫 index、detail 的视图函数
    # 我们用品那个app_name来指定命名空间，如果你忘了在 blog\urls.py 中添加这一句，接下来你可能会得到一个 NoMatchReversed 异常

    path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    # 这个归档视图对应的 URL 和 detail 视图函数对应的 URL 是类似的，
    # 这在之前我们讲过，django 会从用户访问的 URL 中自动提取 URL 路径参数转换器 <type:name> 规则捕获的值，
    # 然后传递给其对应的视图函数。例如如果用户想查看 2017 年 3 月下的全部文章，
    # 他访问 /archives/2017/3/，那么 URL 转换器就会根据规则捕获到 2017 和 3 这两个整数，
    # 然后作为参数传给 archive 视图函数， archive 视图函数的实际调用为：archive(request, year=2017, month=3)
    # 接下来在 inclusions 文件夹下找到 archives 的模板，修改超链接的 href 属性，让用户点击超链接后跳转到文章归档页面
    # path('archives/<int:year>/<int:month>', views.archive, name='archive'),
    # path('categories/<int:pk>/', views.category, name='category'),
    path('categories/<int:pk>', views.CategoryView.as_view(), name='category'),
    path('tage/<int:pk>/', views.tag, name='tag'),
    path('search/', views.search, name='search'),
]

# 这个两行的函数体现了这个过程。它首先接受了一个名为 request 的参数，
# 这个 request 就是 django 为我们封装好的 HTTP 请求，它是类 HttpRequest 的一个实例。
# 然后我们便直接返回了一个 HTTP 响应给用户，这个 HTTP 响应也是 django 帮我们封装好的，
# 它是类 HttpResponse 的一个实例，只是我们给它传了一个自定义的字符串参数
# django 匹配 URL 模式是在 blogproject 目录（即 settings.py 文件所在的目录）的 urls.py 下的，
# 所以我们要把 blog 应用下的 urls.py 文件包含到 blogproject\urls.py 里去

templates/base.html
{% load blog_extras %}
{% load static %}
{% load blog_extras %}
<!DOCTYPE html>
<html>
<head>
    <title>一堆丸崽在摸鱼</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    {#    <!--#}
    {#    我们引入的路径放在一个奇怪的符号里面，用{ %% }包裹起来的叫做模板标签，我们前面说过用{ {} }包裹起来的叫做模板变量，#}
    {#    其作用就是在最终选人的模板里显示由视图函数传过来的变量值，这里我们使用的模板标签的功能则类似于函数，#}
    {#    例如这里的 static 模板标签，它把跟在后面的字符串 'css/bootstrap.min.css' 转换成正确的文件引入路径#}
    {#    这样 css 和 js 文件才能被正确加载，样式才能正常显示#}
    {#    为了能在模板中使用 { % static % } 模板标签，别忘了在最顶部 { % load static % }#}
    {#    static 模板标签位于 static模块中，只有通过 load 模板标签将该模块引入后，才能在模板中使用 { % static % } 标签#}
    {#    -->#}

    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!--这里使用的是一个外部文件，不是我们本地的文件，所以无法使用模板标签-->
    <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">
    {#    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">#}
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">

    <style>
        /*搜索关键词gaoliang*/
        span.highlighted{
            color: red;
        }
        .codehilite {
            padding: 0;
        }

        .hjs-ln-numbers {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;

            text-align: center;
            color: #ccc;
            border-right: 1px solid #ccc;
            vertical-align: top;
            padding-right: 5px;
        }

        .hljs-ln-n {
            width: 30px;
        }

        .hljs-ln .hljs-ln-code {
            padding-left: 10px;
            white-space: pre;
        }
    </style>

    {#    <!--#}
    {#    可以看到 { % static % } 标签的作用实际就是把后面的字符串加了一个 /static/ 前缀，比如 { % static 'blog/css/pace.css' % }#}
    {#    最终渲染的值是 /static/blog/css/pace.css#}
    {#    而 /static/ 前缀是我们在 settings.py 文件中通过 STATIC_URL = '/static/' 指定的#}
    {#    我们用{ % static % }是因为当前url的前缀是static，如果我们/static/改成/resource/#}
    {#        如果你没有引入模板标签，那么你要改n个地方，如果你用了，你只需要在setting.py中的STATIC_URL = '/static/' 变成 '/resource/'即可#}
    {#    -->#}

    <!-- js -->
    {#    <script src="{% static 'blog/js/jqery-2.1.3.min.js' %}"></script>#}
    {#    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>#}
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
    <script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
    <script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
    <script>
        hljs.initHighlightingOnLoad();
        hljs.initLineNumbersOnLoad();
    </script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}" style="background-image: -webkit-linear-gradient(bottom, rgb(33,180,226), rgb(255,124,216)); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">沐兮的小窝</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>
{##}
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
{#                        <ul class="nav navbar-nav navbar-right">#}
{#                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>#}
{#                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>#}
{#                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>#}
{#                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>#}
{#                        </ul>#}
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box" style="width: 170px;height: 50px">
{#                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>#}
{#                    <div id="search-form" class="search-form">#}
                        <form role="search" method="get" id="searchform"
{#                              action="{% url 'haystack_search' %}">#}
                              action="{% url 'blog:search' %}">
                            <input type="search" name="q" placeholder="遇之所见 · 喜之所爱" required>
{#                            特别注意这里 <input type="search" name="q" placeholder="搜索" required> 中的 name 属性，#}
{#                            当用户在这个 input 中输入搜索内容并提交表单后，键入的数据会以键值对的形式提交服务器，#}
{#                            这个键的名字就是通过 name 属性指定的。这样服务器就可以根据 name 的值来取得用户输入的内容#}
{#                            用户输入了搜索关键词并点击了搜索按钮后，数据就被发送给了 Django 后台服务器。#}
{#                            表单的 action 属性的值为 {% url 'blog:search' %}（虽然我们还没有写这个视图函数），#}
{#                            表明用户提交的结果将被发送给 blog 应用下 search 视图函数对应的 URL。#}
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
{#                    </div>#}
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
        {#        这里 django 会通过全局上下文自动把 messages 变量传给模板，这个变量里存储我们发送的消息内容，然后就是循环显示消息了。#}
        {#        这里我们使用了 bootstrap 的一个 alert 组件，为其设置不同的 class 会显示不同的颜色，所以之前添加消息时传入的 extra_tags 就派上了用场。#}
        {#        比如这里 alert-{ { message.tags } }，当传入的是 success 时，类名就为 alert-success，这时显示的消息背景颜色就是绿色，传入的是 dangerous，则显示的就是红色#}
    {% endif %}
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}

                {% show_recent_posts %}
                {% show_archives %}
                {% show_categories %}
                {% show_tags %}

                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
		<div class="rss">
			<p style="background-image: -webkit-linear-gradient(bottom, rgb(205,235,139), rgb(168,73,163)); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">友链</p>
			<div clss="col-md-4" style="font-size:15px;">
				<p><a href="https://xiaoyes.cn" title="毕计状" style="background-image: -webkit-linear-gradient(bottom, rgb(239,1,124), rgb(102,182,252)); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">路远的博客</a></p>
				<p><a href="https://www.cnblogs.com/selisen/" title="李森" style="background-image: -webkit-linear-gradient(bottom, rgb(203,96,179), rgb(255,48,25)); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">开心小市民</a>
			</div>
		</div>
            </aside>
            {#            <!--#}
            {#            这里 block 也是一个模板标签，其作用是占位。#}
            {#            比如这里的 { % block main % }{ % endblock main % } 是一个占位框，#}
            {#            main 是我们给这个 block 取的名字。下面我们会看到 block 标签的作用。#}
            {#            同时我们也在 aside 标签下加了一个 { % block toc % }{ % endblock toc % } 占位框，#}
            {#            因为 detail.html 中 aside 标签下会多一个目录栏。#}
            {#            当 { % block toc % }{ % endblock toc % } 中没有任何内容时，{ % block toc % }{ % endblock toc % } 在模板中不会显示。#}
            {#            但当其中有内容是，模板就会显示 block 中的内容#}
            {#            -->#}
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">
                <p style="text-align: center">&copy 2021-2022</p>
                <p style="text-align: center">
                    <a href="https://beian.miit.gov.cn" title="#" target="_blank">豫ICP备2021031354号-1</a>
                </p>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
{#            <li><a href="full-width.html">博客</a></li>#}
{#            <li><a href="about.html">关于</a></li>#}
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}j"></script>

</body>
</html>