blog/urls.py
#!/usr/bin/python

"""
编写者:沫
时间:08:45 下午
"""
from django.urls import path
from . import views

# django 的做法是把不同的网址对应的处理函数写在一个 urls.py 文件里，当用户访问某个网址时，django 就去会这个文件里找
# 如果找到这个网址，就会调用和它绑定在一起的处理函数（叫做视图函数）
# 我们首先从 django.urls 导入了 path 函数，又从当前目录下导入了 views 模块。
# 然后我们把网址和处理函数的关系写在了 urlpatterns 列表里
# 绑定关系的写法是把网址和对应的处理函数作为参数传给 path 函数（第一个参数是网址，第二个参数是处理函数）
# 另外我们还传递了另外一个参数 name，这个参数的值将作为处理函数 index 的别名，这在以后会用到

# 在 blogProject 目录下（即 settings.py 所在的目录），原本就有一个 urls.py 文件，这是整个工程项目的 URL 配置文件。
# 而我们这里新建了一个 urls.py 文件，且位于 blog 应用下。这个文件将用于 blog 应用相关的 URL 配置，这样便于模块化管理。不要把两个文件搞混了
# 首页视图匹配的 URL 去掉域名后其实就是一个空的字符串。
# 对文章详情视图而言，每篇文章对应着不同的 URL。
# 比如我们可以把文章详情页面对应的视图设计成这个样子：
# 当用户访问 <网站域名>/posts/1/ 时，显示的是第一篇文章的内容，
# 而当用户访问 <网站域名>/posts/2/ 时，显示的是第二篇文章的内容，
# 这里数字代表了第几篇文章，也就是数据库中 Post 记录的 id

app_name = 'blog'
urlpatterns = [
    # path('', views.index, name='index'),
    # 前面已经说过每一个 URL 对应着一个视图函数，这样当用户访问这个 URL 时，
    # Django 就知道调用哪个视图函数去处理这个请求了。
    # 在 Django 中 URL 模式的配置方式就是通过 url 函数将 URL 和视图函数绑定。
    # 比如 path('', views.index, name='index')，它的第一个参数是 URL 模式，第二个参数是视图函数 index。
    # 对 url 函数来说，第二个参数传入的值必须是一个函数。
    # 而 IndexView 是一个类，不能直接替代 index 函数。
    # 好在将类视图转换成函数视图非常简单，只需调用类视图的 as_view() 方法即可（至于 as_view 方法究竟是如何将一个类转换成一个函数的目前不必关心，
    # 只需要在配置 URL 模式是调用 as_view 方法就可以了。
    # 具体的实现我们以后会专门开辟一个专栏分析类视图的源代码，到时候就能看出 django 使用的魔法了）。
    path('', views.IndexView.as_view(), name='index'),

    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    # 这里 'posts/<int:pk>/' 刚好匹配我们上面定义的 URL 规则。
    # 这条规则的含义是，以 posts/ 开头，后跟一个整数，并且以 / 符号结尾，如 posts/1/、 posts/255/ 等都是符合规则的，
    # 此外这里 <int:pk> 是 django 路由匹配规则的特殊写法，
    # 其作用是从用户访问的 URL 里把匹配到的数字捕获并作为关键字参数传给其对应的视图函数 detail。
    # 比如当用户访问 posts/255/ 时（注意 django 并不关心域名，而只关心去掉域名后的相对 URL），<int:pk> 匹配 255，
    # 那么这个 255 会在调用视图函数 detail 时被传递进去，其参数名就是冒号后面指定的名字 pk，
    # 实际上视图函数的调用就是这个样子：detail(request, pk=255)。
    # 我们这里必须从 URL 里捕获文章的 id，因为只有这样我们才能知道用户访问的究竟是哪篇文章
    # django 的路由匹配规则有很多类型，除了这里的 int 整数类型，还有 str 字符类型、uuid 等，
    # 可以通过官方文档了解：https://docs.djangoproject.com/en/2.2/topics/http/urls/#path-converters
    # 此外我们通过 app_name='blog' 告诉 django 这个 urls.py 模块是属于 blog 应用的，这种技术叫做视图函数命名空间
    # 我们看到 blog\urls.py 目前有两个视图函数，
    # 并且通过 name 属性给这些视图函数取了个别名，分别是 index、detail。
    # 但是一个复杂的 django 项目可能不止这些视图函数，例如一些第三方应用中也可能有叫 index、detail 的视图函数
    # 我们用品那个app_name来指定命名空间，如果你忘了在 blog\urls.py 中添加这一句，接下来你可能会得到一个 NoMatchReversed 异常

    path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    # 这个归档视图对应的 URL 和 detail 视图函数对应的 URL 是类似的，
    # 这在之前我们讲过，django 会从用户访问的 URL 中自动提取 URL 路径参数转换器 <type:name> 规则捕获的值，
    # 然后传递给其对应的视图函数。例如如果用户想查看 2017 年 3 月下的全部文章，
    # 他访问 /archives/2017/3/，那么 URL 转换器就会根据规则捕获到 2017 和 3 这两个整数，
    # 然后作为参数传给 archive 视图函数， archive 视图函数的实际调用为：archive(request, year=2017, month=3)
    # 接下来在 inclusions 文件夹下找到 archives 的模板，修改超链接的 href 属性，让用户点击超链接后跳转到文章归档页面
    # path('archives/<int:year>/<int:month>', views.archive, name='archive'),
    # path('categories/<int:pk>/', views.category, name='category'),
    path('categories/<int:pk>', views.CategoryView.as_view(), name='category'),
    path('tage/<int:pk>/', views.tag, name='tag'),
    path('search/', views.search, name='search'),
]

# 这个两行的函数体现了这个过程。它首先接受了一个名为 request 的参数，
# 这个 request 就是 django 为我们封装好的 HTTP 请求，它是类 HttpRequest 的一个实例。
# 然后我们便直接返回了一个 HTTP 响应给用户，这个 HTTP 响应也是 django 帮我们封装好的，
# 它是类 HttpResponse 的一个实例，只是我们给它传了一个自定义的字符串参数
# django 匹配 URL 模式是在 blogproject 目录（即 settings.py 文件所在的目录）的 urls.py 下的，
# 所以我们要把 blog 应用下的 urls.py 文件包含到 blogproject\urls.py 里去

comments/urls.py
#!/usr/bin/python

# 编写者:沫
# 时间:09:06 下午
from django.urls import path

from . import views

app_name = 'comments'
urlpatterns = [
    path('comment/<int:post_pk>', views.comment, name='comment'),
]

comments/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Comment(models.Model):
    name = models.CharField('名字', max_length=50)
    email = models.EmailField('邮箱')
    url = models.URLField('网址', blank=True)
    text = models.TextField('内容')
    created_time = models.DateTimeField('创建时间', default=timezone.now)
    post = models.ForeignKey('blog.Post', verbose_name='文章', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        ordering = ['-created_time']

    def __str__(self):
        return '{}: {}'.format(self.name, self.text[:20])
    # 评论会保存评论用户的 name（名字）、email（邮箱）、url（个人网站，可以为空），用户发表的内容将存放在 text 字段里，created_time 记录评论时间。
    # 最后，这个评论是关联到某篇文章（Post）的，由于一个评论只能属于一篇文章，一篇文章可以有多个评论，是一对多的关系，因此这里我们使用了 ForeignKey

comments/forms.py
#!/usr/bin/python

# 编写者:沫
# 时间:07:05 下午
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']
    # 要使用 django 的表单功能，我们首先导入 forms 模块。
    # django 的表单类必须继承自 forms.Form 类或者 forms.ModelForm 类。
    # 如果表单对应有一个数据库模型（例如这里的评论表单对应着评论模型），那么使用 ModelForm 类会简单很多，
    # 这是 django 为我们提供的方便。之后我们在表单的内部类 Meta 里指定一些和表单相关的东西。
    # model = Comment 表明这个表单对应的数据库模型是 Comment 类。
    # fields = ['name', 'email', 'url', 'text'] 指定了表单需要显示的字段，
    # 这里我们指定了 name、email、url、text 需要显示

comments/views.py
from blog.models import Post
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.contrib import messages

from .forms import CommentForm


# Create your views here.


@require_POST
def comment(request, post_pk):
    # 先获取被评论的文章，因为后面需要把评论和被评论的文章关联起来。
    # 这里我们使用了 django 提供的一个快捷函数 get_object_or_404，
    # 这个函数的作用是当获取的文章（Post）存在时，则获取；否则返回 404 页面给用户
    post = get_object_or_404(Post, pk=post_pk)

    # django 将用户提交的数据封装在 request.POST 中，这是一个类字典对象。
    # 我们利用这些数据构造了 CommentForm 的实例，这样就生成了一个绑定了用户提交数据的表单
    form = CommentForm(request.POST)

    # 当调用 form.is_valid() 方法时，django 自动帮我们检查表单的数据是否符合格式要求。
    if form.is_valid():
        # 检查到数据是合法的，调用表单的 save 方法保存数据到数据库，
        # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例，但还不保存评论数据到数据库。
        comment = form.save(commit=False)

        # 将评论和被评论的文章关联起来
        comment.post = post

        # 最终将评论数据保存进数据库，调用模型实例的 save 方法
        comment.save()

        messages.add_message(request, messages.SUCCESS, '发表成功', extra_tags='success')
        # 这里导入 django 的 messages 模块，使用 add_message 方法增加了一条消息，消息的第一个参数是当前请求，
        # 因为当前请求携带用户的 cookie，django 默认将详细存储在用户的 cookie 中。
        # 第二个参数是消息级别，评论发表成功的消息设置为 messages.SUCCESS，这是 django 已经默认定义好的一个整数，消息级别也可以自己定义。
        # 紧接着传入消息的内容，最后 extra_tags 给这条消息打上额外的标签，标签值可以在展示消息时使用，
        # 比如这里我们会把这个值用在模板中的 HTML 标签的 class 属性，增加样式

        # 重定向到 post 的详情页，实际上当 redirect 函数接收一个模型的实例时，它会调用这个模型实例的 get_absolute_url 方法，
        # 然后重定向到 get_absolute_url 方法返回的 URL。
        return redirect(post)

    # 检查到数据不合法，我们渲染一个预览页面，用于展示表单的错误。
    # 注意这里被评论的文章 post 也传给了模板，因为我们需要根据 post 来生成表单的提交地址
    context = {
        'post': post,
        'form': form,
    }
    messages.add_message(request, messages.ERROR, '发表失败,请修改之后发表', extra_tags='danger')
    return render(request, 'comments/preview.html', context=context)

# 这个评论视图相比之前的一些视图复杂了很多，主要是处理评论的过程更加复杂。具体过程在代码中已有详细注释，这里仅就视图中出现了一些新的知识点进行讲解。
# 首先视图函数被 require_POST 装饰器装饰，从装饰器的名字就可以看出，其作用是限制这个视图只能通过 POST 请求触发，因为创建评论需要用户通过表单提交的数据，而提交表单通常都是限定为 POST 请求，这样更加安全。
# 另外我们使用了 redirect 快捷函数。
# 这个函数位于 django.shortcuts 模块中，它的作用是对 HTTP 请求进行重定向（即用户访问的是某个 URL，但由于某些原因，服务器会将用户重定向到另外的 URL）。
# redirect 既可以接收一个 URL 作为参数，也可以接收一个模型的实例作为参数（例如这里的 post）。
# 如果接收一个模型的实例，那么这个实例必须实现了 get_absolute_url 方法，这样 redirect 会根据 get_absolute_url 方法返回的 URL 值进行重定向。
# 如果用户提交的数据合法，我们就将评论数据保存到数据库，否则说明用户提交的表单包含错误，我们将渲染一个 preview.html 页面，来展示表单中的错误，以便用户修改后重新提交

templates/comments/inclusions/_form.html
<form action="{% url 'comments:comment' post.pk %}" method="post" class="comment-form">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-4">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
            {{ form.name }}
            {{ form.name.errors }}
        </div>
        <div class="col-md-4">
            <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
            {{ form.email }}
            {{ form.email.errors }}
        </div>
        <div class="col-md-4">
            <label for="{{ form.url.id_for_label }}">{{ form.url.label }}:</label>
            {{ form.url }}
            {{ form.url.errors }}
        </div>
        <div class="col-md-12">
            <label for="{{ form.text.id_for_label }}">{{ form.text.label }}:</label>
            {{ form.text }}
            {{ form.text.errors }}
            <button type="submit" class="comment-btn">发表</button>
        </div>
    </div>
</form>
{#首先 HTML 的 form 标签有 2 个重要的属性，action 和 method。action 指定表单内容提交的地址，#}
{#这里我们提交给 comments:comment 视图函数对应的 URL（后面会创建这个视图函数并绑定对应的 URL），#}
{#模板标签 url 的用法在 分类、归档和标签页 教程中有详细介绍。method 指定提交表单时的 HTTP 请求类型，一般表单提交都是使用 POST#}
{#然后我们看到 { % csrf_token % }，这个模板标签在表单渲染时会自动渲染为一个隐藏类型的 HTML input 控件，#}
{#其值为一个随机字符串，作用主要是为了防护 CSRF（跨站请求伪造）攻击。{ % csrf_token % } 在模板中渲染出来的内容大概如下所示#}
{#< input type="hidden" name="csrfmiddlewaretoken" value="KH9QLnpQPv2IBcv3oLsksJXdcGvKSnC8t0mTfRSeNIlk5T1G1MBEIwVhK4eh6gIZ" >#}
{#CSRF 攻击是一种常见的 Web 攻击手段。攻击者利用用户存储在浏览器中的 cookie，向目标网站发送 HTTP 请求，#}
{#这样在目标网站看来，请求来自于用户，而实际发送请求的人却是攻击者。#}
{#例如假设我们的博客支持登录功能（目前没有），并使用 cookie（或者 session）记录用户的登录状态，且评论表单没有 csrf token 防护。#}
{#用户登录了我们的博客后，又去访问了一个小电影网站，小电影网站有一段恶意 JavaScript 脚本，它读取用户的 cookie，并构造了评论表单的数据，#}
{#然后脚本使用这个 cookie 向我们的博客网站发送一条 POST 请求，django 就会认为这是来自该用户的评论发布请求，便会在后台创建一个该用户的评论，而这个用户全程一脸懵逼。#}
{#CSRF 的一个防范措施是，对所有访问网站的用户颁发一个令牌（token），#}
{#对于敏感的 HTTP 请求，后台会校验此令牌，确保令牌的确是网站颁发给指定用户的。#}
{#因此，当用户访问别的网站时，虽然攻击者可以拿到用户的 cookie，但是无法取得证明身份的令牌，因此发过来的请求便不会被受理。#}
{#以上是对 CSRF 攻击和防护措施的一个简单介绍，更加详细的讲解请使用搜索引擎搜索相关资料#}
{#show_comment_form 模板标签给模板传递了一个模板变量 form，它是 CommentForm 的一个实例，表单的字段 {{ form.name }}、{{ form.email }}、{{ form.url }} 等将自动渲染成表单控件，例如 <input> 控件。#}
{#注意到表单的定义中并没有定义 name、email、url 等属性，那它们是哪里来的呢？#}
{#看到 CommentForm 中 Meta 下的 fields，django 会自动将 fields 中声明的模型字段设置为表单的属性。#}
{#{{ form.name.errors }}、{{ form.email.errors }} 等将渲染表单对应字段的错误（如果有的话），#}
{#例如用户 email 格式填错了，那么 django 会检查用户提交的 email 的格式，然后将格式错误信息保存到 errors 中，模板便将错误信息渲染显示。#}
{#{{ form.xxx.label }} 用来获取表单的 label，之前说过，django 根据表单对应的模型中字段的 verbose_name 参数生成。#}
{#然后我们就可以在 detail.html 中使用这个模板标签来渲染表单了，注意在使用前记得先 {% load comments_extras %} 这个模块#}

templates/comments/inclusions/_list.html
<h3>评论列表,共<span>{{ comment_count }}</span>条评论</h3>
<ul class="comment-list list-unstyled">
    {% for comment in comment_list %}
        <li class="comment-item">
        <span class="nickname">{{ comment.name }}</span>
        <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
        <div class="text">
            {{ comment.text|linebreaks }}
        </div>
        </li>
    {% empty %}
        暂无评论
    {% endfor %}
</ul>
{#要注意这里 {{ comment.text|linebreaks }} 中对评论内容使用的过滤器 linebreaks，浏览器会将换行以及连续的多个空格合并为一个空格。#}
{#如果用户评论的内容中有换行，浏览器会将换行替换为空格，从而显示的用户评论内容就会挤成一堆。#}
{#linebreaks 过滤器预先将换行符替换为 br HTML 标签，这样内容就能换行显示了#}