blog/urls.py
#!/usr/bin/python

"""
编写者:沫
时间:08:45 下午
"""
from django.urls import path
from . import views

# django 的做法是把不同的网址对应的处理函数写在一个 urls.py 文件里，当用户访问某个网址时，django 就去会这个文件里找
# 如果找到这个网址，就会调用和它绑定在一起的处理函数（叫做视图函数）
# 我们首先从 django.urls 导入了 path 函数，又从当前目录下导入了 views 模块。
# 然后我们把网址和处理函数的关系写在了 urlpatterns 列表里
# 绑定关系的写法是把网址和对应的处理函数作为参数传给 path 函数（第一个参数是网址，第二个参数是处理函数）
# 另外我们还传递了另外一个参数 name，这个参数的值将作为处理函数 index 的别名，这在以后会用到

# 在 blogProject 目录下（即 settings.py 所在的目录），原本就有一个 urls.py 文件，这是整个工程项目的 URL 配置文件。
# 而我们这里新建了一个 urls.py 文件，且位于 blog 应用下。这个文件将用于 blog 应用相关的 URL 配置，这样便于模块化管理。不要把两个文件搞混了
# 首页视图匹配的 URL 去掉域名后其实就是一个空的字符串。
# 对文章详情视图而言，每篇文章对应着不同的 URL。
# 比如我们可以把文章详情页面对应的视图设计成这个样子：
# 当用户访问 <网站域名>/posts/1/ 时，显示的是第一篇文章的内容，
# 而当用户访问 <网站域名>/posts/2/ 时，显示的是第二篇文章的内容，
# 这里数字代表了第几篇文章，也就是数据库中 Post 记录的 id

app_name = 'blog'
urlpatterns = [
    # path('', views.index, name='index'),
    # 前面已经说过每一个 URL 对应着一个视图函数，这样当用户访问这个 URL 时，
    # Django 就知道调用哪个视图函数去处理这个请求了。
    # 在 Django 中 URL 模式的配置方式就是通过 url 函数将 URL 和视图函数绑定。
    # 比如 path('', views.index, name='index')，它的第一个参数是 URL 模式，第二个参数是视图函数 index。
    # 对 url 函数来说，第二个参数传入的值必须是一个函数。
    # 而 IndexView 是一个类，不能直接替代 index 函数。
    # 好在将类视图转换成函数视图非常简单，只需调用类视图的 as_view() 方法即可（至于 as_view 方法究竟是如何将一个类转换成一个函数的目前不必关心，
    # 只需要在配置 URL 模式是调用 as_view 方法就可以了。
    # 具体的实现我们以后会专门开辟一个专栏分析类视图的源代码，到时候就能看出 django 使用的魔法了）。
    path('', views.IndexView.as_view(), name='index'),

    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    # 这里 'posts/<int:pk>/' 刚好匹配我们上面定义的 URL 规则。
    # 这条规则的含义是，以 posts/ 开头，后跟一个整数，并且以 / 符号结尾，如 posts/1/、 posts/255/ 等都是符合规则的，
    # 此外这里 <int:pk> 是 django 路由匹配规则的特殊写法，
    # 其作用是从用户访问的 URL 里把匹配到的数字捕获并作为关键字参数传给其对应的视图函数 detail。
    # 比如当用户访问 posts/255/ 时（注意 django 并不关心域名，而只关心去掉域名后的相对 URL），<int:pk> 匹配 255，
    # 那么这个 255 会在调用视图函数 detail 时被传递进去，其参数名就是冒号后面指定的名字 pk，
    # 实际上视图函数的调用就是这个样子：detail(request, pk=255)。
    # 我们这里必须从 URL 里捕获文章的 id，因为只有这样我们才能知道用户访问的究竟是哪篇文章
    # django 的路由匹配规则有很多类型，除了这里的 int 整数类型，还有 str 字符类型、uuid 等，
    # 可以通过官方文档了解：https://docs.djangoproject.com/en/2.2/topics/http/urls/#path-converters
    # 此外我们通过 app_name='blog' 告诉 django 这个 urls.py 模块是属于 blog 应用的，这种技术叫做视图函数命名空间
    # 我们看到 blog\urls.py 目前有两个视图函数，
    # 并且通过 name 属性给这些视图函数取了个别名，分别是 index、detail。
    # 但是一个复杂的 django 项目可能不止这些视图函数，例如一些第三方应用中也可能有叫 index、detail 的视图函数
    # 我们用品那个app_name来指定命名空间，如果你忘了在 blog\urls.py 中添加这一句，接下来你可能会得到一个 NoMatchReversed 异常

    path('archives/<int:year>/<int:month>/', views.archive, name='archive'),
    # 这个归档视图对应的 URL 和 detail 视图函数对应的 URL 是类似的，
    # 这在之前我们讲过，django 会从用户访问的 URL 中自动提取 URL 路径参数转换器 <type:name> 规则捕获的值，
    # 然后传递给其对应的视图函数。例如如果用户想查看 2017 年 3 月下的全部文章，
    # 他访问 /archives/2017/3/，那么 URL 转换器就会根据规则捕获到 2017 和 3 这两个整数，
    # 然后作为参数传给 archive 视图函数， archive 视图函数的实际调用为：archive(request, year=2017, month=3)
    # 接下来在 inclusions 文件夹下找到 archives 的模板，修改超链接的 href 属性，让用户点击超链接后跳转到文章归档页面
    # path('archives/<int:year>/<int:month>', views.archive, name='archive'),
    # path('categories/<int:pk>/', views.category, name='category'),
    path('categories/<int:pk>', views.CategoryView.as_view(), name='category'),
    path('tage/<int:pk>/', views.tag, name='tag'),
    path('search/', views.search, name='search'),
]

# 这个两行的函数体现了这个过程。它首先接受了一个名为 request 的参数，
# 这个 request 就是 django 为我们封装好的 HTTP 请求，它是类 HttpRequest 的一个实例。
# 然后我们便直接返回了一个 HTTP 响应给用户，这个 HTTP 响应也是 django 帮我们封装好的，
# 它是类 HttpResponse 的一个实例，只是我们给它传了一个自定义的字符串参数
# django 匹配 URL 模式是在 blogproject 目录（即 settings.py 文件所在的目录）的 urls.py 下的，
# 所以我们要把 blog 应用下的 urls.py 文件包含到 blogproject\urls.py 里去

blog/views.py
import re
import markdown
from django.shortcuts import render
from django.http import HttpResponse

from .models import Post
from django.shortcuts import render, get_object_or_404
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from .models import Post, Category, Tag
from django.views.generic import ListView, DetailView
from pure_pagination.mixins import PaginationMixin
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import redirect


# Create your views here.
# 这里我们不再是直接把字符串传给 HttpResponse 了，而是调用 django 提供的 render 函数。
# 这个函数根据我们传入的参数来构造 HttpResponse
# 我们首先吧http请求传了进去，让后render根据第二参数的值blog/index.html找到这个模板文件并读取模板中的内容
# 之后render根据我们传入的context参数的值吧模板中的变量替换成我们传递的变量的值{{title}}和{{welcome}}被替换成了context字典中对应的值
# 最终我们的html模板中的内容字符串被传递给httpResponse对象并返回浏览器（django在render函数里隐式地帮我们完成了这个过程

# def index(request):
#     """
#     主页视图函数中通过 Post.objects.all() 获取全部文章，而在归档和分类视图中，
#     我们不再使用 all 方法获取全部文章，而是使用 filter 来根据条件过滤
#     """
#     post_list = Post.objects.all().order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})
#     # 这里我们使用 all() 方法从数据库里获取了全部的文章，存在了 post_list 变量里。
#     # all 方法返回的是一个 QuerySet（可以理解成一个类似于列表的数据结构），
#     # 由于通常来说博客文章列表是按文章发表时间倒序排列的，即最新的文章排在最前面，
#     # 所以我们紧接着调用了 order_by 方法对这个返回的 queryset 进行排序。
#     # 排序依据的字段是 created_time，即文章的创建时间。
#     # - 号表示逆序，如果不加 - 则是正序。
#     # 接着如之前所做，我们渲染了 blog\index.html 模板文件，并且把包含文章列表数据的 post_list 变量传给了模板


# def detail(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     # 增加阅读量
#     post.increase_views()
#     md = markdown.Markdown(
#         extensions=[
#             'markdown.extensions.extra',  # 基础扩展
#             'markdown.extensions.codehilite',  # 语法高亮扩展
#             # 'markdown.extensions.toc',  # 生成目录扩展
#             # 需要引入ToxExtension和slugify
#             # extensions 中的 toc 拓展不再是字符串 markdown.extensions.toc ，
#             # 而是 TocExtension 的实例。TocExtension 在实例化时其 slugify 参数可以接受一个函数，
#             # 这个函数将被用于处理标题的锚点值。Markdown 内置的处理方法不能处理中文标题，
#             # 所以我们使用了 django.utils.text 中的 slugify 方法，该方法可以很好地处理中文
#
#             TocExtension(slugify=slugify),
#
#             # Markdown 在设置锚点时利用的是标题的值，由于通常我们的标题都是中文，Markdown 没法处理，
#             # 所以它就忽略的标题的值，而是简单地在后面加了个 _1 这样的锚点值。
#             # 为了解决这一个问题，需要修改一下传给 extentions 的参数
#             # 和之前不同的是，extensions 中的 toc 拓展不再是字符串 markdown.extensions.toc ，
#             # 而是 TocExtension 的实例。TocExtension 在实例化时其 slugify 参数可以接受一个函数，
#             # 这个函数将被用于处理标题的锚点值。Markdown 内置的处理方法不能处g理中文标题，
#             # 所以我们使用了 django.utils.text 中的 slugify 方法，该方法可以很好地处理中文
#         ]
#     )
#     # 和之前的代码不同，我们没有直接用 markdown.markdown() 方法来渲染 post.body 中的内容，
#     # 而是先实例化了一个 markdown.Markdown 对象 md，和 markdown.markdown() 方法一样，
#     # 也传入了 extensions 参数。接着我们便使用该实例的 convert 方法将 post.body 中的 Markdown 文本解析成 HTML 文本。
#     # 而一旦调用该方法后，实例 md 就会多出一个 toc 属性，这个属性的值就是内容的目录，
#     # 我们把 md.toc 的值赋给 post.toc 属性（要注意这个 post 实例本身是没有 toc 属性的，我们给它动态添加了 toc 属性，这就是 Python 动态语言的好处）
#     """正则匹配目录是否存在"""
#     post.body = md.convert(post.body)
#     m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
#     post.toc = m.group(1) if m is not None else ''
#     # 这里我们正则表达式去匹配生成的目录中包裹在 ul 标签中的内容，
#     # 如果不为空，说明目录，就把 ul 标签中的值提取出来（目的是只要包含目录内容的最核心部分，多余的 HTML 标签结构丢掉）赋值给 post.toc；
#     # 否则，将 post 的 toc 置为空字符串，然后我们就可以在模板中通过判断 post.toc 是否为空
#
#     # post.body = md.convert(post.body)
#     # post.toc = md.toc
#
#     # 这样我们在模板中显示{{post.body}}的时候，就不再是原始的Markdown文本了，
#     # 而是解析过后的HTML文本。注意这里我们给markdown解析函数传递了额外的参数extensions，
#     # 它是对Markdown语法的拓展，这里使用了三个拓展，分别是xtra、codehilite、toc。extra本身包含很多基础拓展，
#     # 而codehilite是语法高亮拓展，这为后面的实现代码高亮功能提供基础，而toc则允许自动生成目录
#     # markdown.markdown()方法把post.bod中的Markdown文本解析成了HTML文本。同时我们还给该方法提供了一个extensions的额外参数。其中
#     # markdown.extensions.toc就是自动生成目录的拓展（这里可以看出我们有先见之明，如果你之前没有添加的话记得现在添加进去）
#     # 在渲染 Markdown 文本时加入了 toc 拓展后，就可以在文中插入目录了。方法是在书写 Markdown 文本时，在你想生成目录的地方插入`[TOC] 标记即可
#     return render(request, 'blog/detail.html', context={'post': post})
#
#     # 视图函数很简单，它根据我们从 URL 捕获的文章 id（也就是 pk，这里 pk 和 id 是等价的）获取数据库中文章 id 为该值的记录，
#     # 然后传递给模板。注意这里我们用到了从 django.shortcuts 模块导入的 get_object_or_404 方法，
#     # 其作用就是当传入的 pk 对应的 Post 在数据库存在时，就返回对应的 post，如果不存在，就给用户返回一个 404 错误，表明用户请求的文章不存在


# def index(request):
#     """
#     主页视图函数中通过 Post.objects.all() 获取全部文章，而在归档和分类视图中，
#     我们不再使用 all 方法获取全部文章，而是使用 filter 来根据条件过滤
#     """
#     post_list = Post.objects.all().order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})


def archive(request, year, month):
    post_list = Post.objects.filter(
        created_time__year=year,
        created_time__month=month,
    ).order_by('-created_time')


# 这里使用了模型管理器（objects）的 filter 方法来过滤文章。
# 由于是按照日期归档，因此这里根据文章发表的年和月来过滤。
# 具体来说，就是根据 created_time 的 year 和 month 属性过滤，筛选出文章发表在对应的 year 年和 month 月的文章。
# 注意这里 created_time 是 Python 的 date 对象，其有一个 year 和 month 属性，
# 我们在 页面侧边栏：使用自定义模板标签 使用过这个属性。Python 中调用属性的方式通常是 created_time.year，
# 但是由于这里作为方法的参数列表，所以 django 要求我们把点替换成了两个下划线，即 created_time__year。
# 同时和 index 视图中一样，我们对返回的文章列表进行了排序。此外由于归档页面和首页展示文章的形式是一样的，
# 因此直接复用了 index.html 模板
# def category(request, pk):
#     cate = get_object_or_404(Category, pk=pk)
#     post_list = Post.objects.filter(category=cate).order_by('-created_time')
#     # return render(request, 'blog/index.html', context={'post_list': post_list})
#     return render(request, 'blog/index.html', context={'post_list': post_list})
#     # 这里我们首先根据传入的 pk 值（也就是被访问的分类的 id 值）从数据库中获取到这个分类。get_object_or_404 函数和 detail 视图中一样，
#     # 其作用是如果用户访问的分类不存在，则返回一个 404 错误页面以提示用户访问的资源不存在。
#     # 然后我们通过模型管理器的 filter 方法过滤出了该分类下的全部文章。同样也和首页视图中一样对返回的文章列表进行了排序


def tag(request, pk):
    t = get_object_or_404(Tag, pk=pk)
    post_list = Post.objects.filter(tags=t).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})


class IndexView(PaginationMixin, ListView):
    model = Post
    template_name = 'blog/index.html'
    content_object_name = 'post_list'
    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 5
    # 要写一个视图首先要继承django提供的某个类视图,至于继承那个视图,需要根据视图功能而定
    # 例如这里的IndexView的功能是那个数据库中获取文章(post)列表,ListView就是从数据库中获取某个模型列表数据的,所以IndexView继承ListView
    # 然后就是通过一些属性来指定这个视图函数需要做的事情,这里我们指定三个属性
    # model: 将model指定为post,告诉django我要获取数据模型是post
    # template_name: 指定这个视图渲染的模板
    # context_object_name: 指定获取的模板列表数据保存的变量名,这个变量会被传递给模板
    # 我们与index视图函数对比一下
    # index首先通过Post.object.all()从数据库中获取文章(post)列表数据吗,并保存到post_list变量中.
    # 在类视图中这个过程ListView已经帮我们做了,我们只需要告诉ListView去数据库中获取的模型是Post,而不是Comment或者其它什么模型,即指定model=post
    # 将获得的模型数据列表保存到post_list里,即指定context_object_name='post_list'
    # 然后渲染blog/index.html模板文件,index视图函数中使用render函数,但这个过程ListView已经帮我们做了,我们只需要指定那个模板即可


class CategoryView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)
        # 和 IndexView 不同的地方是，我们覆写了父类的 get_queryset 方法。
        # 该方法默认获取指定模型的全部列表数据。为了获取指定分类下的文章列表数据，我们覆写该方法，改变它的默认行为。
        # 首先是需要根据从 URL 中捕获的分类 id（也就是 pk）获取分类，
        # 这和 category 视图函数中的过程是一样的。
        # 不过注意一点的是，在类视图中，从 URL 捕获的路径参数值保存在实例的 kwargs 属性（是一个字典）里，非路径参数值保存在实例的 args 属性（是一个列表）里。
        # 所以我们使了 self.kwargs.get('pk') 来获取从 URL 捕获的分类 id 值。
        # 然后我们调用父类的 get_queryset 方法获得全部文章列表，
        # 紧接着就对返回的结果调用了 filter 方法来筛选该分类下的全部文章并返回。


class PostDetailView(DetailView):
    # 这些属性的含义和 ListView 是一样的
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response = super(PostDetailView, self).get(request, *args, **kwargs)

        # 将文章阅读量 +1
        # 注意 self.object 的值就是被访问的文章 post
        self.object.increase_views()

        # 视图必须返回一个 HttpResponse 对象
        return response

    # def get_object(self, queryset=None):
    #     # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
    #     post = super().get_object(queryset=None)
    #     md = markdown.Markdown(extensions=[
    #         'markdown.extensions.extra',
    #         'markdown.extensions.codehilite',
    #         # 记得在顶部引入 TocExtension 和 slugify
    #         TocExtension(slugify=slugify),
    #     ])
    #     post.body = md.convert(post.body)

    #     m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    #     post.toc = m.group(1) if m is not None else ''

    #     return post
    # PostDetailView 稍微复杂一点，主要是等价的 detail 视图函数本来就比较复杂，下面来一步步对照 detail 视图函数中的代码讲解。
    # 首先我们为 PostDetailView 类指定了一些属性的值，这些属性的含义和 ListView 中是一样的，这里不再重复讲解。
    # 紧接着我们覆写了 get 方法。这对应着 detail 视图函数中将 post 的阅读量 +1 的那部分代码。事实上，你可以简单地把 get 方法的调用看成是 detail 视图函数的调用。
    # 接着我们又复写了 get_object 方法。这对应着 detail 视图函数中根据文章的 id（也就是 pk）获取文章，然后对文章的 post.body 进行 Markdown 解析的代码部分。
    # 你也许会被这么多方法搞乱，为了便于理解，你可以简单地把 get 方法看成是 detail 视图函数，至于其它的像 get_object、get_context_data 都是辅助方法，
    # 这些方法最终在 get 方法中被调用，这里你没有看到被调用的原因是它们隐含在了 super(PostDetailView, self).get(request, *args, **kwargs) 即父类 get 方法的调用中。
    # 最终传递给浏览器的 HTTP 响应就是 get 方法返回的 HttpResponse 对象。


def search(request):
    q = request.GET.get('q')

    if not q:
        error_msg = "请输入搜索关键词"
        messages.add_message(request, messages.ERROR, error_msg, extra_tags='danger')
        return redirect('blog:index')

    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'post_list': post_list})

templates/blog/inclusions/_archives.html
<div class="widget widget-archives">
    <h3 class="widget-title">归档</h3>
    <ul>
        {% for date in data_list %}
            <li>
                <a href="{% url 'blog:archive' date.year date.month %}">
{#                    <!--#}
{#                    这里 { % url % } 这个模板标签的作用是解析视图函数 blog:archive 对应的 URL 模式，并#}
{#                    把 URL 模式中的年和月替换成 date.year，date.month 的值#}
{#                    { % url % } 模板标签接收的第一个参数为被解析视图函数的端点值，这个端点值由 2 部分组成，中间由冒号分隔。#}
{#                    第一部分为在应用的 urls.py 中指定的 app_name 的值（充当命名空间，这样即使不同 app 下有相同的视图函数名，也不会冲突），#}
{#                    第二部分 path 函数中传入的 name 参数的值。#}
{#                    比如在 blog 应用的 urls.py 模块，我们指定了 app_name = 'blog'，#}
{#                    archive 视图函数的 url 模式为 path('archives/<int:year>/<int:month>/', views.archive, name='archive')，#}
{#                    因此对应的端点值为 blog:archive#}
{#                    { % url % } 模板标签接收的其它参数为 URL 路径参数，即 URL 模式中路径参数转换器需要捕获的值。#}
{#                    例如 archive 视图函数对应的 URL 模式为 archives/<int:year>/<int:month>/，#}
{#                    假设 date.year=2017，date.month=5，那么 { % url 'blog:archive' date.year date.month % } 模板标签返回的值为 /archives/2017/5/#}
{#                    我们把超链接的 href 属性设置为 /archives/{ { date.year } }/{ { date.month } }/ 同样可以达到目的，#}
{#                    但是这种写法是硬编码的。虽然现在 blog:archive 视图函数对应的 URL 模式是这种形式，但是如果哪天这个模式改变了呢？#}
{#                    如果使用了硬编码的写法，那你需要把每一处 /archives/{ { date.year } }/{ { date.month } }/ 修改为新的模式。#}
{#                    但如果使用了 { % url % } 模板标签，则不用做任何修改#}
{#                    -->#}
                    {{ date.year }}年{{ date.month }}月
                </a>
{#                <!--由于 date_list 中的每个元素都是 Python 的 date 对象，所以可以引用 year 和 month 属性来获取年份和月份-->#}
            </li>
        {% empty %}
            暂无归档
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_categories.html
<div class="widget widget-category">
    <h3 class="widget-title">分类</h3>
    <ul>
        {% for category in category_list %}
            <li>
                <a href="{% url 'blog:category' category.pk %}">{{ category.name }}
                    <span class="post-count">
{#                        (13)#}
{#                        <!-- 显示的是该分类下的文章数目，这个特性会在接下来会讲解如何实现，目前暂时用占位数据代替吧-->#}
                        ({{ category.num_posts }})
                    </span>
                </a>
            </li>
        {% empty %}
            暂无分类
        {% endfor %}
    </ul>
</div>

templates/blog/inclusions/_recent_posts.html
<div class="widget widget-recent-posts">
    <h3 class="widget-title">最新文章</h3>
    <ul>
        {% for post in recent_post_list %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
        {% empty %}
        暂无文章
        {% endfor %}
{#    <!--很简单，循环由 show_recent_posts 传递的模板变量 recent_post_list 即可，和 index.html 中循环显示文章列表是一样的-->#}
    </ul>
</div>

templates/blog/inclusions/_tags.html
<div class="widget widget-archives">
    <h3 class="widget-title">标签云</h3>
    <ul>
        {% for tag in tag_list %}
            <li>
                <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}
                    <span class="post-count">
                       ({{ tag.num_posts }})
                    </span>
                </a>
            </li>
        {% empty %}
            暂无标签
        {% endfor %}
    </ul>
</div>